/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as MyTasksRouteImport } from './routes/my-tasks'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IamRouteImport } from './routes/iam'
import { Route as ForceChangePasswordRouteImport } from './routes/force-change-password'
import { Route as BenchmarksRouteImport } from './routes/benchmarks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdTimelineInteractiveRouteImport } from './routes/projects_.$projectId.timeline-interactive'
import { Route as ProjectsProjectIdStagesStageIdRouteImport } from './routes/projects_.$projectId.stages.$stageId'

const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const MyTasksRoute = MyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IamRoute = IamRouteImport.update({
  id: '/iam',
  path: '/iam',
  getParentRoute: () => rootRouteImport,
} as any)
const ForceChangePasswordRoute = ForceChangePasswordRouteImport.update({
  id: '/force-change-password',
  path: '/force-change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BenchmarksRoute = BenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/$reportId',
  path: '/$reportId',
  getParentRoute: () => ReportsRoute,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsProjectIdTimelineInteractiveRoute =
  ProjectsProjectIdTimelineInteractiveRouteImport.update({
    id: '/projects_/$projectId/timeline-interactive',
    path: '/projects/$projectId/timeline-interactive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProjectsProjectIdStagesStageIdRoute =
  ProjectsProjectIdStagesStageIdRouteImport.update({
    id: '/projects_/$projectId/stages/$stageId',
    path: '/projects/$projectId/stages/$stageId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/force-change-password': typeof ForceChangePasswordRoute
  '/iam': typeof IamRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/projects/$projectId/timeline-interactive': typeof ProjectsProjectIdTimelineInteractiveRoute
  '/projects/$projectId/stages/$stageId': typeof ProjectsProjectIdStagesStageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/force-change-password': typeof ForceChangePasswordRoute
  '/iam': typeof IamRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects': typeof ProjectsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/projects/$projectId/timeline-interactive': typeof ProjectsProjectIdTimelineInteractiveRoute
  '/projects/$projectId/stages/$stageId': typeof ProjectsProjectIdStagesStageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/benchmarks': typeof BenchmarksRoute
  '/force-change-password': typeof ForceChangePasswordRoute
  '/iam': typeof IamRoute
  '/login': typeof LoginRoute
  '/my-tasks': typeof MyTasksRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/projects/': typeof ProjectsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/projects_/$projectId/timeline-interactive': typeof ProjectsProjectIdTimelineInteractiveRoute
  '/projects_/$projectId/stages/$stageId': typeof ProjectsProjectIdStagesStageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/benchmarks'
    | '/force-change-password'
    | '/iam'
    | '/login'
    | '/my-tasks'
    | '/projects'
    | '/reports'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects/'
    | '/reports/'
    | '/projects/$projectId/timeline-interactive'
    | '/projects/$projectId/stages/$stageId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/benchmarks'
    | '/force-change-password'
    | '/iam'
    | '/login'
    | '/my-tasks'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects'
    | '/reports'
    | '/projects/$projectId/timeline-interactive'
    | '/projects/$projectId/stages/$stageId'
  id:
    | '__root__'
    | '/'
    | '/benchmarks'
    | '/force-change-password'
    | '/iam'
    | '/login'
    | '/my-tasks'
    | '/projects'
    | '/reports'
    | '/projects/$projectId'
    | '/reports/$reportId'
    | '/projects/'
    | '/reports/'
    | '/projects_/$projectId/timeline-interactive'
    | '/projects_/$projectId/stages/$stageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BenchmarksRoute: typeof BenchmarksRoute
  ForceChangePasswordRoute: typeof ForceChangePasswordRoute
  IamRoute: typeof IamRoute
  LoginRoute: typeof LoginRoute
  MyTasksRoute: typeof MyTasksRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  ProjectsProjectIdTimelineInteractiveRoute: typeof ProjectsProjectIdTimelineInteractiveRoute
  ProjectsProjectIdStagesStageIdRoute: typeof ProjectsProjectIdStagesStageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-tasks': {
      id: '/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof MyTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iam': {
      id: '/iam'
      path: '/iam'
      fullPath: '/iam'
      preLoaderRoute: typeof IamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/force-change-password': {
      id: '/force-change-password'
      path: '/force-change-password'
      fullPath: '/force-change-password'
      preLoaderRoute: typeof ForceChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/benchmarks': {
      id: '/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof BenchmarksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects_/$projectId/timeline-interactive': {
      id: '/projects_/$projectId/timeline-interactive'
      path: '/projects/$projectId/timeline-interactive'
      fullPath: '/projects/$projectId/timeline-interactive'
      preLoaderRoute: typeof ProjectsProjectIdTimelineInteractiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$projectId/stages/$stageId': {
      id: '/projects_/$projectId/stages/$stageId'
      path: '/projects/$projectId/stages/$stageId'
      fullPath: '/projects/$projectId/stages/$stageId'
      preLoaderRoute: typeof ProjectsProjectIdStagesStageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProjectsRouteChildren {
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsReportIdRoute: ReportsReportIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BenchmarksRoute: BenchmarksRoute,
  ForceChangePasswordRoute: ForceChangePasswordRoute,
  IamRoute: IamRoute,
  LoginRoute: LoginRoute,
  MyTasksRoute: MyTasksRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  ProjectsProjectIdTimelineInteractiveRoute:
    ProjectsProjectIdTimelineInteractiveRoute,
  ProjectsProjectIdStagesStageIdRoute: ProjectsProjectIdStagesStageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
